name: Tests

on:
  push:
    branches: [ master, develop ]
    paths-ignore:
      - 'docs_src/**'
      - 'docs/**'
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          toolchain: stable

      - name: Cache build target
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-rustc_${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rustc_${{ steps.toolchain.outputs.rustc_hash }

      - name: Build rpfm-lib
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --lib
      
      - name: Build rpfm-cli
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --bin rpfm_cli

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --lib
