name: Tests

on:
  push:
    branches: [ master, develop ]
    paths-ignore:
      - 'docs_src/**'
      - 'docs/**'
  pull_request:
    branches: [ master, develop ]
    paths-ignore:
      - 'docs_src/**'
      - 'docs/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cache build target
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build rpfm-lib
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --lib
      
      - name: Build rpfm-cli
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --bin rpfm_cli

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --lib
